steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh submission-instance-183200 --zone=asia-southeast1-a --command="
          export PATH=/root/.nvm/versions/node/v20.17.0/lib/node_modules && \
          cd ~/forum-api && \
          git pull origin main && \
          npm install && \
          npm run sequelize:setup && \
          pm2 restart forum-api
        "

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
