name: Continuous Deployment
 
on: 
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"
    - name: SSH and deploy app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          if [ ! -d "~/forum-api" ]; then
            git clone https://github.com/X-Hozmi/forum-api.git ~/forum-api
          fi
          cd ~/forum-api
          git pull origin main
          npm install
          npm run sequelize:setup
          pm2 restart forum-api