name: Continuous Deployment
 
on: 
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          if [ ! -d "~/forum-api" ]; then
            git clone https://github.com/X-Hozmi/forum-api.git ~/forum-api
          fi
          cd ~/forum-api
          if ! command -v npm &> /dev/null
          then
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          if ! command -v pm2 &> /dev/null
          then
            sudo npm install -g pm2
          fi
          git pull origin main
          npm install
          npm run sequelize:setup
          pm2 restart forum-api