name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
   
    services:
      postgres:
        image: postgres
        env:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: mysecretpassword
         POSTGRES_DB: forumapi
         
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install sequelize and test
      env:
        CI: true
        HOST: localhost
        PORT: 5000
        DBPROTOCOL: postgres
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: mysecretpassword
        PGDATABASE: forumapi
        PGPORT: 5432
        PGHOST_TEST: localhost
        PGUSER_TEST: postgres
        PGPASSWORD_TEST: mysecretpassword
        PGDATABASE_TEST: forumapi
        PGPORT_TEST: 5432
        ACCESS_TOKEN_KEY: secret
        REFRESH_TOKEN_KEY: terces
        ACCESS_TOKEN_AGE: 3600
      run: |
        npm install
        npm run sequelize:setup
        npm run sequelize:setup:test
        npm run test